spring:
  application:
    name: agentbot
  config:
    import: "optional:file:${AGENTBOT_CONFIG:./config/agentbot.yml}"

server:
  address: ${server.ip:127.0.0.1}
  port: ${server.port:8080}
  servlet:
    session:
      timeout: 24h
    encoding:
      charset: UTF-8
      enabled: true
      force: true









